name: task_manager_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State Meanagement
  flutter_bloc: ^8.1.6
  # Dependency Injection 
  get_it: ^8.0.2
  # Functional Programming
  equatable: ^2.0.5
  dartz: ^0.10.1
  # External Api
  http: ^1.2.2
  http_interceptor: ^2.0.0
  internet_connection_checker: ^1.0.0+1
  # Testing
  test: ^1.25.7
  # Local Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4

flutter:
  uses-material-design: true
